{"errorMessage": "cannot load library 'libpango-1.0-0': libpango-1.0-0: cannot open shared object file: No such file or directory.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'libpango-1.0-0'", "errorType": "OSError", "requestId": "", "stackTrace": ["  File \"/var/lang/lib/python3.11/importlib/__init__.py\", line 126, in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n", "  File \"<frozen importlib._bootstrap>\", line 1204, in _gcd_import\n", "  File \"<frozen importlib._bootstrap>\", line 1176, in _find_and_load\n", "  File \"<frozen importlib._bootstrap>\", line 1147, in _find_and_load_unlocked\n", "  File \"<frozen importlib._bootstrap>\", line 690, in _load_unlocked\n", "  File \"<frozen importlib._bootstrap_external>\", line 940, in exec_module\n", "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n", "  File \"/var/task/main.py\", line 16, in <module>\n    import weasyprint\n", "  File \"/var/lang/lib/python3.11/site-packages/weasyprint/__init__.py\", line 430, in <module>\n    from .css import preprocess_stylesheet  # noqa: I001, E402\n", "  File \"/var/lang/lib/python3.11/site-packages/weasyprint/css/__init__.py\", line 28, in <module>\n    from .computed_values import COMPUTER_FUNCTIONS\n", "  File \"/var/lang/lib/python3.11/site-packages/weasyprint/css/computed_values.py\", line 9, in <module>\n    from ..text.ffi import FROM_UNITS, ffi, pango\n", "  File \"/var/lang/lib/python3.11/site-packages/weasyprint/text/ffi.py\", line 478, in <module>\n    pango = _dlopen(\n", "  File \"/var/lang/lib/python3.11/site-packages/weasyprint/text/ffi.py\", line 463, in _dlopen\n    return ffi.dlopen(names[0], flags)  # pragma: no cover\n", "  File \"/var/lang/lib/python3.11/site-packages/cffi/api.py\", line 150, in dlopen\n    lib, function_cache = _make_ffi_library(self, name, flags)\n", "  File \"/var/lang/lib/python3.11/site-packages/cffi/api.py\", line 834, in _make_ffi_library\n    backendlib = _load_backend_lib(backend, libname, flags)\n", "  File \"/var/lang/lib/python3.11/site-packages/cffi/api.py\", line 829, in _load_backend_lib\n    raise OSError(msg)\n"]}